spring:
    profiles:
        active: local
    config:
        import: application-s3.yml
---
app:
    jwt:
        jwt-secret-key: "umjarijwtsecretkeyumjarijwtsecretkeyumjarijwtsecretkey"
        jwt-expiration-in-ms: 36000000
