spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/umjari?serverTimezone=UTC
    username: umjari
    password: devpassword
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql