spring:
    profiles:
        active: local
    config:
        import: optional:application-s3.yml, optional:application-mail.yml
    data:
      web:
        pageable:
            one-indexed-parameters: true
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
---
app:
    jwt:
        jwt-secret-key: "umjarijwtsecretkeyumjarijwtsecretkeyumjarijwtsecretkey"
        jwt-expiration-in-ms: 36000000
