spring:
    config:
        activate:
            on-profile: docker
    datasource:
        url: jdbc:postgresql://postgres:5432/umjari?serverTimezone=UTC
        username: umjari
        password: devpassword
    sql:
        init:
            mode: always
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql
springdoc:
    version: 'v1'
    api-docs:
        path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    paths-to-match:
        - /api/v1/**
