spring:
  config:
    activate:
      on-profile: local
app:
  jwt:
    jwt-secret-key: "umjarijwtsecretkeyumjarijwtsecretkeyumjarijwtsecretkey"
    jwt-expiration-in-ms: 36000000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/umjari?serverTimezone=UTC
    username: umjari
    password: devpassword
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/umjari?serverTimezone=UTC
    username: umjari
    password: devpassword
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
---
