version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/build/
      overwrite: yes
permissions:
    - object: /
      pattern: "**"
      owner: ubuntu
      group: ubuntu

hooks:
    AfterInstall:
        - location: stop.sh
          timeout: 60
          runas: ec2-user
    ApplicationStart:
        - location: start.sh
          timeout: 60
          runas: ec2-user
