name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  CD:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    environment: prod

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'termuin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Make directory for zip
      run: mkdir deploy

    - name: Copy jar files
      run: cp ./build/libs/*.jar ./deploy/

    - name: Copy deploy scripts
      run: cp -r ./scripts/* ./deploy/

    - name: Zip deploy directory
      run: zip -r -qq -j ./umjari-server.zip ./deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Copy zip file to AWS S3
      run: |
        aws s3 cp \
        --region ${{ secrets.AWS_REGION }} \
        --acl private \
        ./umjari-server.zip s3://${{ secrets.AWS_DEPLOY_BUCKET_NAME }}/
    - name: Deploy to EC2
      run: |
        aws deploy create-deployment \
        --application-name umjari-deploy \
        --deployment-group-name umjari-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=${{ secrets.AWS_DEPLOY_BUCKET_NAME }},bundleType=zip,key=umjari-server.zip \
        --region ${{ secrets.AWS_REGION }}
