# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: umjari-test
          POSTGRES_USER: umjari-test
          POSTGRES_PASSWORD: devpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Check ktlint with Gradle
      run: |
        ./gradlew ktlintCheck
        cat build/reports/ktlint/**/*.txt

    - name: Build with Gradle
      run: ./gradlew build -x test -x ktlintCheck

    - name: Test with Gradle
      run: ./gradlew test

    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.8.1
      with:
        jacoco-csv-file: build/customJacocoReportDir/test/jacocoTestReport.csv
